import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#2B2B2B",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#dec0b7",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "outline": "#a58b83",
        "outline-variant": "#57423b",
        "surface-tint": "#ffb59c",
        "primary": "#ffb59c",
        "on-primary": "#5c1900",
        "primary-container": "#e46f45",
        "on-primary-container": "#511500",
        "inverse-primary": "#a23e18",
        "secondary": "#fdb69e",
        "on-secondary": "#4f2414",
        "secondary-container": "#6b3a28",
        "on-secondary-container": "#e9a58e",
        "tertiary": "#72d4ee",
        "on-tertiary": "#003641",
        "tertiary-container": "#329db6",
        "on-tertiary-container": "#002e38",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59c",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#822801",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#fdb69e",
        "on-secondary-fixed": "#351003",
        "on-secondary-fixed-variant": "#6b3a28",
        "tertiary-fixed": "#adecff",
        "tertiary-fixed-dim": "#72d4ee",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#004e5d",
        "background": "#131313",
        "bg": "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "muted": "#8B8B8B",
        "text": "#EAEAEA",
        "accent": "#C85A32",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "1.5rem",
        "margin": "1.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        serif: ["var(--font-lora)", "serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        "title-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
